package com.aiagent.tools;

import cn.hutool.core.io.FileUtil;
import cn.hutool.core.util.StrUtil;
import cn.hutool.json.JSONArray;
import cn.hutool.json.JSONObject;
import cn.hutool.json.JSONUtil;
import com.aiagent.files.GeneratedFileContext;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;

import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Generates lightweight chart artifacts that can be embedded into reports.
 */
public class ChartGenerationTool {

    private static final int WIDTH = 960;
    private static final int HEIGHT = 540;
    private static final ZoneId REPORT_ZONE = ZoneId.of("Asia/Shanghai");
    private static final DateTimeFormatter REPORT_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Tool(description = "Generate chart artifacts only when structured numeric data is suitable for visualization. Supports bar for comparison/ranking, line for trends over time, and pie for composition/share. Outputs a chart image path and an HTML preview; final downloadable reports should be generated by ReportArtifactTool.", returnDirect = false)
    public String generateChart(
            @ToolParam(description = "Chart file name, for example: market-comparison.svg") String fileName,
            @ToolParam(description = "Chart title") String title,
            @ToolParam(description = "Chart type: bar, line, or pie. Use line for time trends, bar for comparisons/rankings, pie for composition/share.") String chartType,
            @ToolParam(description = "JSON array/object. Prefer [{\"label\":\"A\",\"value\":12.3}].") String dataJson,
            @ToolParam(description = "One or two sentences explaining the chart insight") String insight) {
        try {
            List<DataPoint> points = parseData(dataJson);
            String normalizedType = normalizeChartType(chartType);
            String dataError = validateChartData(points, normalizedType);
            if (dataError != null) {
                return chartDataError(dataError);
            }

            String safeSvgName = normalizeFileName(fileName, "chart", ".svg");
            String baseName = safeSvgName.replaceFirst("\\.svg$", "");
            Path svgPath = GeneratedFileContext.resolve("chart", safeSvgName);
            Path previewPath = GeneratedFileContext.resolve("preview", baseName + ".html");

            FileUtil.mkdir(svgPath.getParent().toString());
            FileUtil.mkdir(previewPath.getParent().toString());

            String svg = switch (normalizedType) {
                case "line" -> buildLineSvg(title, insight, points);
                case "pie" -> buildPieSvg(title, insight, points);
                default -> buildBarSvg(title, insight, points);
            };

            FileUtil.writeString(svg, svgPath.toFile(), StandardCharsets.UTF_8);
            FileUtil.writeString(buildPreviewHtml(title, insight, svg), previewPath.toFile(), StandardCharsets.UTF_8);

            JSONObject result = JSONUtil.createObj();
            result.set("success", true);
            result.set("type", "chart");
            result.set("chartType", normalizedType);
            result.set("title", defaultIfBlank(title, "图表分析"));
            result.set("insight", defaultIfBlank(insight, ""));
            result.set("svgPath", svgPath.toString());
            result.set("previewPath", previewPath.toString());
            result.set("files", files(
                    file("图表预览", "html", previewPath.toString(), true)
            ));
            result.set("generatedAt", LocalDateTime.now(REPORT_ZONE).format(REPORT_TIME_FORMATTER));
            return result.toString();
        } catch (Exception e) {
            JSONObject error = JSONUtil.createObj();
            error.set("success", false);
            error.set("code", "CHART_GENERATION_FAILED");
            error.set("message", e.getMessage());
            return error.toString();
        }
    }

    private String chartDataError(String message) {
        JSONObject error = JSONUtil.createObj();
        error.set("success", false);
        error.set("code", "INSUFFICIENT_CHART_DATA");
        error.set("message", message);
        error.set("suggestion", "不要生成图表。请改用文字说明或表格，并明确标注数据未披露/不可比。");
        return error.toString();
    }

    private String validateChartData(List<DataPoint> points, String chartType) {
        if (points == null || points.isEmpty()) {
            return "未提供可解析的真实数值数据，不能生成图表。";
        }
        if ("line".equals(chartType) && points.size() < 2) {
            return "折线图至少需要两个时间点或阶段数据。";
        }
        boolean hasNonZero = points.stream().anyMatch(point -> Math.abs(point.value()) > 0.000001);
        if (!hasNonZero) {
            return "所有数值均为 0 或缺失，不能生成容易误导的图表。";
        }
        if ("pie".equals(chartType) && points.stream().noneMatch(point -> point.value() > 0)) {
            return "饼图需要正数占比或构成数据。";
        }
        return null;
    }

    private String buildBarSvg(String title, String insight, List<DataPoint> points) {
        double maxAbs = points.stream().map(p -> Math.abs(p.value())).max(Comparator.naturalOrder()).orElse(1D);
        if (maxAbs <= 0) {
            maxAbs = 1D;
        }
        int left = 150;
        int right = 110;
        int top = 96;
        int rowGap = Math.max(24, Math.min(46, 330 / Math.max(points.size(), 1)));
        int barHeight = Math.max(12, Math.min(26, rowGap - 10));
        int maxBarWidth = WIDTH - left - right;

        StringBuilder svg = svgStart(title, insight);
        svg.append("<g transform=\"translate(0,0)\">");
        for (int i = 0; i < points.size(); i++) {
            DataPoint point = points.get(i);
            int y = top + i * rowGap;
            int barWidth = (int) Math.round(Math.abs(point.value()) / maxAbs * maxBarWidth);
            String color = point.value() >= 0 ? "#059669" : "#dc2626";
            svg.append("<text x=\"24\" y=\"").append(y + 17).append("\" class=\"label\">")
                    .append(escape(point.label())).append("</text>");
            svg.append("<rect x=\"").append(left).append("\" y=\"").append(y).append("\" width=\"")
                    .append(Math.max(2, barWidth)).append("\" height=\"").append(barHeight)
                    .append("\" rx=\"6\" fill=\"").append(color).append("\"/>");
            svg.append("<text x=\"").append(left + Math.max(8, barWidth) + 12).append("\" y=\"")
                    .append(y + 17).append("\" class=\"value\">").append(format(point.value())).append("</text>");
        }
        svg.append("</g>").append(svgEnd());
        return svg.toString();
    }

    private String buildLineSvg(String title, String insight, List<DataPoint> points) {
        double min = points.stream().map(DataPoint::value).min(Comparator.naturalOrder()).orElse(0D);
        double max = points.stream().map(DataPoint::value).max(Comparator.naturalOrder()).orElse(1D);
        if (Double.compare(min, max) == 0) {
            max = min + 1D;
        }
        int left = 80;
        int top = 96;
        int chartWidth = WIDTH - 150;
        int chartHeight = 310;

        StringBuilder polyline = new StringBuilder();
        StringBuilder dots = new StringBuilder();
        for (int i = 0; i < points.size(); i++) {
            DataPoint point = points.get(i);
            double ratio = (point.value() - min) / (max - min);
            int x = left + (int) Math.round((double) i / Math.max(points.size() - 1, 1) * chartWidth);
            int y = top + chartHeight - (int) Math.round(ratio * chartHeight);
            polyline.append(x).append(',').append(y).append(' ');
            dots.append("<circle cx=\"").append(x).append("\" cy=\"").append(y).append("\" r=\"5\" fill=\"#2563eb\"/>")
                    .append("<text x=\"").append(x - 22).append("\" y=\"").append(top + chartHeight + 34)
                    .append("\" class=\"axis\">").append(escape(shorten(point.label(), 8))).append("</text>");
        }

        StringBuilder svg = svgStart(title, insight);
        svg.append("<line x1=\"").append(left).append("\" y1=\"").append(top + chartHeight)
                .append("\" x2=\"").append(left + chartWidth).append("\" y2=\"").append(top + chartHeight)
                .append("\" stroke=\"#cbd5e1\"/>");
        svg.append("<line x1=\"").append(left).append("\" y1=\"").append(top)
                .append("\" x2=\"").append(left).append("\" y2=\"").append(top + chartHeight)
                .append("\" stroke=\"#cbd5e1\"/>");
        svg.append("<polyline fill=\"none\" stroke=\"#2563eb\" stroke-width=\"4\" stroke-linecap=\"round\" stroke-linejoin=\"round\" points=\"")
                .append(polyline.toString().trim()).append("\"/>");
        svg.append(dots).append(svgEnd());
        return svg.toString();
    }

    private String buildPieSvg(String title, String insight, List<DataPoint> points) {
        List<DataPoint> positivePoints = points.stream()
                .map(point -> new DataPoint(point.label(), Math.max(0D, point.value())))
                .filter(point -> point.value() > 0)
                .limit(8)
                .toList();
        double total = positivePoints.stream().mapToDouble(DataPoint::value).sum();
        if (total <= 0) {
            total = 1D;
        }

        String[] colors = {"#2563eb", "#059669", "#f59e0b", "#dc2626", "#7c3aed", "#0891b2", "#db2777", "#65a30d"};
        int cx = 330;
        int cy = 270;
        int radius = 150;
        double startAngle = -90D;
        StringBuilder svg = svgStart(title, insight);
        if (positivePoints.size() == 1) {
            svg.append("<circle cx=\"").append(cx).append("\" cy=\"").append(cy).append("\" r=\"")
                    .append(radius).append("\" fill=\"").append(colors[0]).append("\"/>");
        } else {
            for (int i = 0; i < positivePoints.size(); i++) {
                DataPoint point = positivePoints.get(i);
                double sweep = point.value() / total * 360D;
                double endAngle = startAngle + sweep;
                double[] start = polar(cx, cy, radius, startAngle);
                double[] end = polar(cx, cy, radius, endAngle);
                int largeArc = sweep > 180D ? 1 : 0;
                svg.append("<path d=\"M ").append(cx).append(' ').append(cy)
                        .append(" L ").append(formatCoordinate(start[0])).append(' ').append(formatCoordinate(start[1]))
                        .append(" A ").append(radius).append(' ').append(radius).append(" 0 ")
                        .append(largeArc).append(" 1 ")
                        .append(formatCoordinate(end[0])).append(' ').append(formatCoordinate(end[1]))
                        .append(" Z\" fill=\"").append(colors[i % colors.length]).append("\"/>");
                startAngle = endAngle;
            }
        }
        svg.append("<circle cx=\"").append(cx).append("\" cy=\"").append(cy).append("\" r=\"72\" fill=\"#ffffff\" opacity=\"0.92\"/>");
        svg.append("<text x=\"").append(cx).append("\" y=\"").append(cy + 5)
                .append("\" text-anchor=\"middle\" class=\"value\">合计 ").append(format(total)).append("</text>");

        int legendX = 560;
        int legendY = 135;
        for (int i = 0; i < positivePoints.size(); i++) {
            DataPoint point = positivePoints.get(i);
            double percent = point.value() / total * 100D;
            int y = legendY + i * 38;
            svg.append("<rect x=\"").append(legendX).append("\" y=\"").append(y - 13)
                    .append("\" width=\"16\" height=\"16\" rx=\"4\" fill=\"").append(colors[i % colors.length]).append("\"/>");
            svg.append("<text x=\"").append(legendX + 26).append("\" y=\"").append(y)
                    .append("\" class=\"label\">").append(escape(shorten(point.label(), 18))).append("</text>");
            svg.append("<text x=\"").append(legendX + 250).append("\" y=\"").append(y)
                    .append("\" class=\"value\">").append(String.format(java.util.Locale.US, "%.1f%%", percent)).append("</text>");
        }
        svg.append(svgEnd());
        return svg.toString();
    }

    private StringBuilder svgStart(String title, String insight) {
        StringBuilder svg = new StringBuilder();
        svg.append("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"").append(WIDTH)
                .append("\" height=\"").append(HEIGHT).append("\" viewBox=\"0 0 ")
                .append(WIDTH).append(' ').append(HEIGHT).append("\">");
        svg.append("<style>")
                .append(".title{font:700 28px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#172033}")
                .append(".subtitle{font:14px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#64748b}")
                .append(".label{font:13px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#334155}")
                .append(".value{font:700 13px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#172033}")
                .append(".axis{font:11px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#64748b}")
                .append("</style>");
        svg.append("<rect width=\"100%\" height=\"100%\" rx=\"18\" fill=\"#f8fafc\"/>");
        svg.append("<rect x=\"18\" y=\"18\" width=\"").append(WIDTH - 36).append("\" height=\"")
                .append(HEIGHT - 36).append("\" rx=\"14\" fill=\"#ffffff\" stroke=\"#e2e8f0\"/>");
        svg.append("<text x=\"36\" y=\"56\" class=\"title\">").append(escape(defaultIfBlank(title, "图表分析"))).append("</text>");
        if (StrUtil.isNotBlank(insight)) {
            svg.append("<text x=\"36\" y=\"82\" class=\"subtitle\">").append(escape(shorten(insight, 88))).append("</text>");
        }
        return svg;
    }

    private String svgEnd() {
        return "<text x=\"36\" y=\"504\" class=\"subtitle\">Generated by AI Agent · " +
                LocalDateTime.now(REPORT_ZONE).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")) +
                "</text></svg>";
    }

    private List<DataPoint> parseData(String dataJson) {
        List<DataPoint> points = new ArrayList<>();
        if (StrUtil.isBlank(dataJson)) {
            return points;
        }
        try {
            Object parsed = JSONUtil.parse(dataJson);
            if (parsed instanceof JSONArray array) {
                for (int i = 0; i < array.size(); i++) {
                    Object item = array.get(i);
                    if (item instanceof JSONObject object) {
                        Double value = numericValue(object);
                        if (value != null) {
                            points.add(new DataPoint(label(object, i), value));
                        }
                    } else {
                        Double value = parseDouble(item);
                        if (value != null) {
                            points.add(new DataPoint("Item " + (i + 1), value));
                        }
                    }
                }
            } else if (parsed instanceof JSONObject object) {
                for (String key : object.keySet()) {
                    Object value = object.get(key);
                    if (value instanceof Number || value instanceof String) {
                        Double number = parseDouble(value);
                        if (number != null) {
                            points.add(new DataPoint(key, number));
                        }
                    }
                }
            }
        } catch (Exception ignored) {
        }
        return points.stream().limit(12).toList();
    }

    private String label(JSONObject object, int index) {
        String[] keys = {"label", "name", "symbol", "title", "category", "日期", "名称", "标的"};
        for (String key : keys) {
            String value = object.getStr(key, "");
            if (StrUtil.isNotBlank(value)) {
                return value;
            }
        }
        return "Item " + (index + 1);
    }

    private Double numericValue(JSONObject object) {
        String[] keys = {
                "value", "price", "changePercent", "change", "score", "amount", "rate",
                "revenue", "income", "profit", "marketCap", "share", "ratio",
                "涨跌幅", "价格", "数值", "营收", "收入", "净利润", "利润", "业绩",
                "金额", "市值", "占比", "比例", "收益率", "增长率", "亿元"
        };
        for (String key : keys) {
            Object value = object.get(key);
            if (value != null) {
                return parseDouble(value);
            }
        }
        return null;
    }

    private Double parseDouble(Object value) {
        if (value instanceof Number number) {
            return number.doubleValue();
        }
        String raw = String.valueOf(value == null ? "" : value).trim();
        if (StrUtil.isBlank(raw)) {
            return null;
        }
        String cleaned = raw
                .replace("%", "")
                .replace(",", "")
                .replaceAll("[^0-9+\\-.]", "");
        if (StrUtil.isBlank(cleaned)) {
            return null;
        }
        try {
            double parsed = Double.parseDouble(cleaned);
            if (raw.contains("亏损") || raw.contains("下降") || raw.contains("减少")) {
                return -Math.abs(parsed);
            }
            return parsed;
        } catch (Exception e) {
            return null;
        }
    }

    private String buildPreviewHtml(String title, String insight, String svg) {
        return """
                <!doctype html>
                <html lang="zh-CN">
                <head>
                  <meta charset="utf-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  <title>%s</title>
                  <style>body{margin:0;background:#edf1f7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;}main{max-width:1040px;margin:24px auto;padding:20px;}svg{width:100%%;height:auto;display:block}.insight{margin-top:14px;color:#334155;background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:14px;line-height:1.7}</style>
                </head>
                <body><main>%s<div class="insight">%s</div></main></body></html>
                """.formatted(escape(defaultIfBlank(title, "图表预览")), svg, escape(defaultIfBlank(insight, "暂无图表解读。")));
    }

    private String normalizeChartType(String chartType) {
        String value = defaultIfBlank(chartType, "bar").toLowerCase();
        if (value.contains("line") || value.contains("折线") || value.contains("trend") || value.contains("趋势")) {
            return "line";
        }
        if (value.contains("pie") || value.contains("饼") || value.contains("占比") || value.contains("构成")) {
            return "pie";
        }
        return "bar";
    }

    private String normalizeFileName(String fileName, String prefix, String extension) {
        String fallback = prefix + "_" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss")) + extension;
        String name = defaultIfBlank(fileName, fallback).trim();
        name = name.replaceAll("[\\\\/:*?\"<>|\\s]+", "_");
        if (!name.toLowerCase().endsWith(extension)) {
            name += extension;
        }
        return name;
    }

    private JSONArray files(JSONObject... files) {
        JSONArray array = JSONUtil.createArray();
        for (JSONObject file : files) {
            array.add(file);
        }
        return array;
    }

    private JSONObject file(String label, String type, String path, boolean previewable) {
        JSONObject file = JSONUtil.createObj();
        file.set("label", label);
        file.set("type", type);
        file.set("path", path);
        file.set("previewable", previewable);
        return file;
    }

    private String format(double value) {
        if (Math.abs(value - Math.rint(value)) < 0.000001) {
            return String.valueOf((long) Math.rint(value));
        }
        return String.format(java.util.Locale.US, "%.2f", value);
    }

    private double[] polar(int cx, int cy, int radius, double angleDegrees) {
        double radians = Math.toRadians(angleDegrees);
        return new double[]{cx + radius * Math.cos(radians), cy + radius * Math.sin(radians)};
    }

    private String formatCoordinate(double value) {
        return String.format(java.util.Locale.US, "%.2f", value);
    }

    private String shorten(String text, int maxLength) {
        String value = defaultIfBlank(text, "");
        return value.length() <= maxLength ? value : value.substring(0, maxLength) + "...";
    }

    private String defaultIfBlank(String value, String fallback) {
        return StrUtil.isBlank(value) ? fallback : value;
    }

    private String escape(String text) {
        return defaultIfBlank(text, "")
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    private record DataPoint(String label, double value) {
    }
}
